# Generated by Django 5.2.8 on 2025-11-25 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rubros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='rubro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='productos.rubros'),
        ),
    ]
