# Generated by Django 5.2.8 on 2025-12-02 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_rubros_producto_rubro'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubros',
            name='imagen',
            field=models.ImageField(null=True, upload_to='rubros'),
        ),
    ]
